name: Build Frontend CI

on: 
  push:
    branches: [ master ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Building Frontend
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: awesome-sphere/as-ci-cd-template@v1
        with:
          repo: as-frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io
          BASE_IMG_NAME: ${{ github.repository }}